### ISSUE TITLE
Room Name

### ISSUE THREAD

**Issue by rv10guy** [rudders/homebridge-http#1]
Is it possible to add the room as a characteristic so that room name does not have to be configured outside of the config.json?

**Comment by apocolipse** [comment]
You configure rooms at the HomeKit level rather than the Accessory level.  MyTouchHome is a pretty good app for managing HomeKit accessories and lets you make "rooms" to put things in 
i.e. i have "Overhead Lights" and "TV Lights" as 4 different light bulbs, in 1 room, in HomeKit I put them all in a room named "Livingroom", and I can "Turn off Living room lights" to affect them all.
